// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/features/1-login/types';

export const SUPABASE_URL = "https://najgdwffjhnqlogfrlqa.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hamdkd2ZmamhucWxvZ2ZybHFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDg3NjgsImV4cCI6MjA2NTQ4NDc2OH0.Qr10qkO19ssS8ZoF7HUULGFVLX_zeFLCFYJNyI97XHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    // Flow type for better compatibility
    flowType: 'pkce',
  },
  global: {
    // Better error handling for network issues
    fetch: (url, options = {}) => {
      // Create abort controller for timeout if not already provided
      const controller = options.signal ? undefined : new AbortController();
      const timeoutId = controller ? setTimeout(() => controller.abort(), 10000) : undefined; // 10 second timeout
      
      return fetch(url, {
        ...options,
        signal: options.signal || controller?.signal,
      }).catch((error) => {
        // Clear timeout if request completes
        if (timeoutId) clearTimeout(timeoutId);
        
        // Map network errors to be more descriptive
        if (error.name === 'AbortError' || error.name === 'TimeoutError') {
          throw new Error('Network request timeout');
        }
        if (error.message?.includes('Failed to fetch') || error.message?.includes('NetworkError')) {
          throw new Error('Network request failed - please check your connection');
        }
        throw error;
      }).finally(() => {
        // Clear timeout on success too
        if (timeoutId) clearTimeout(timeoutId);
      });
    },
  },
});

